# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-15 00:58
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nationalID', models.CharField(max_length=64, unique=True, validators=[django.core.validators.MinLengthValidator(3)])),
                ('name', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(3)])),
                ('street', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('postcode', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=16)),
                ('website', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('budget', models.IntegerField()),
                ('currency', models.CharField(choices=[(b'USD', b'US Dollar'), (b'EUR', b'Euro'), (b'GBP', b'British Pound')], default=b'USD', max_length=3)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('publishDate', models.DateField()),
                ('documents', models.FileField(upload_to=b'uploads/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenderITApp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenderITApp.Company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TenderITApp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_provider', to='TenderITApp.Company')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_receiver', to='TenderITApp.Company')),
            ],
        ),
    ]
