# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-22 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenderITApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
