# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-15 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TenderITApp', '0002_auto_20160315_2357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
    ]
