# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-16 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenderITApp', '0003_auto_20160315_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='documents',
            field=models.FileField(upload_to=b'uploads/%Y/%m/%d/%H/%M/%S/'),
        ),
    ]
