# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-23 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenderITApp', '0003_auto_20160322_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectapplication',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
