# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-16 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TenderITApp', '0004_auto_20160316_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='documents',
        ),
    ]
