# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-16 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TenderITApp', '0005_remove_project_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='publishDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
