# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-02 19:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TenderITApp', '0010_auto_20160229_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_templates',
            name='password',
        ),
        migrations.RemoveField(
            model_name='company_templates',
            name='username',
        ),
        migrations.AddField(
            model_name='company_templates',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
